import type { CSSProperties } from 'react';
import { h, w } from '../../arOzio/dimensions';

/** Figma 718:870 / 718:897 / 748:1353 — queue & treadmill screens (AR Ozio iPad). */
export const rq: Record<string, CSSProperties> = {
  viewportFill: {
    flex: 1,
    minHeight: 0,
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
  },
  sheet: {
    flex: 1,
    minHeight: 0,
    width: '100%',
    maxWidth: w(2120),
    marginLeft: 'auto',
    marginRight: 'auto',
    alignSelf: 'center',
    borderRadius: w(70),
    background: '#080809',
    border: '1px solid #1e1e1e',
    boxSizing: 'border-box',
    overflow: 'hidden',
    position: 'relative',
    boxShadow: 'inset 0 -160px 160px -200px rgba(230, 35, 58, 0.35)',
  },
  sheetGlow: {
    position: 'absolute',
    inset: 0,
    pointerEvents: 'none',
    background: 'radial-gradient(ellipse 80% 55% at 85% 95%, rgba(230, 35, 58, 0.22), transparent 55%)',
  },
  headerRow: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: `${h(40)} ${w(50)}`,
    flexShrink: 0,
    position: 'relative',
    zIndex: 1,
  },
  logoMark: {
    margin: 0,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: '0.28em',
    fontSize: w(37),
    lineHeight: 1,
    letterSpacing: '0.02em',
    textTransform: 'uppercase',
    fontWeight: 400,
  },
  logoAmazing: { color: '#ffffff' },
  logoRed: { color: '#e6233a' },
  namePill: {
    margin: 0,
    padding: `${h(24)} ${w(50)}`,
    borderRadius: w(80),
    fontSize: w(36),
    letterSpacing: '0.05em',
    color: '#fff',
    textTransform: 'uppercase',
    fontWeight: 400,
  },
  centerWrap: {
    flex: 1,
    minHeight: h(400),
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: `${h(20)} ${w(48)}`,
    position: 'relative',
    zIndex: 1,
    boxSizing: 'border-box',
  },
  titleMain: {
    margin: 0,
    textAlign: 'center',
    fontSize: w(82),
    lineHeight: 1.12,
    fontWeight: 400,
    textTransform: 'uppercase',
    color: '#fff',
    maxWidth: w(2000),
  },
  titleAccent: {
    color: '#e6233a',
  },
  subtitle: {
    margin: `${h(20)} 0 0`,
    textAlign: 'center',
    fontSize: w(40),
    lineHeight: 1.5,
    fontWeight: 400,
    color: 'rgba(255,255,255,0.6)',
    textTransform: 'uppercase',
    maxWidth: w(1400),
  },
  subtitleStrong: {
    color: '#fff',
  },
  footerRow: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'nowrap',
    gap: w(32),
    width: '100%',
    flexShrink: 0,
    paddingTop: h(8),
    boxSizing: 'border-box',
  },
  /** Left: outline / transparent; Right: filled grey (Figma 718:895 / 718:924). */
  btnWide: {
    flex: '1 1 0',
    minWidth: 0,
    minHeight: h(120),
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: w(48),
    border: '1px solid rgba(255,255,255,0.35)',
    background: 'transparent',
    color: '#fff',
    fontSize: w(48),
    fontWeight: 400,
    textTransform: 'uppercase',
    fontFamily: 'inherit',
    cursor: 'pointer',
    boxSizing: 'border-box',
    padding: `${h(32)} ${w(24)}`,
  },
  btnWideSolid: {
    flex: '1 1 0',
    minWidth: 0,
    minHeight: h(120),
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: w(48),
    border: '1px solid rgba(255,255,255,0.12)',
    background: 'rgba(255,255,255,0.08)',
    color: '#fff',
    fontSize: w(48),
    fontWeight: 400,
    textTransform: 'uppercase',
    fontFamily: 'inherit',
    cursor: 'pointer',
    boxSizing: 'border-box',
    padding: `${h(32)} ${w(24)}`,
  },
};
