import type { CSSProperties } from 'react';
import { h, w } from '../../arOzio/dimensions';
import { ui } from '../../ui/tokens';

/** Figma 718:870 / 718:897 / 748:1353 — queue & treadmill screens (AR Ozio iPad). */
export const rq: Record<string, CSSProperties> = {
  viewportFill: {
    flex: 1,
    minHeight: 0,
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
  },
  sheet: {
    flex: 1,
    minHeight: 0,
    width: '100%',
    maxWidth: w(2120),
    marginLeft: 'auto',
    marginRight: 'auto',
    alignSelf: 'stretch',
    display: 'flex',
    flexDirection: 'column',
    boxSizing: 'border-box',
    boxShadow: 'inset 0 -160px 160px -200px rgba(230, 35, 58, 0.35)',
  },
  sheetGlow: {
    position: 'absolute',
    inset: 0,
    pointerEvents: 'none',
    background: 'radial-gradient(ellipse 80% 55% at 85% 95%, rgba(230, 35, 58, 0.22), transparent 55%)',
  },
  /** Prepare screen (718:828): cooler blue tint. */
  prepareSheet: {
    background:
      'radial-gradient(ellipse 70% 48% at 78% 92%, rgba(89, 126, 255, 0.24), rgba(13, 20, 48, 0) 60%), #111216',
  },
  prepareSheetGlow: {
    position: 'absolute',
    inset: 0,
    pointerEvents: 'none',
    background:
      'radial-gradient(ellipse 80% 56% at 84% 95%, rgba(86, 132, 255, 0.28), transparent 58%)',
  },
  /** Figma 1773:512 — readiness screen before the first runner starts. */
  readyRoot: {
    flex: 1,
    minHeight: 0,
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    maxWidth: '100%',
    paddingLeft: h(8),
    paddingRight: h(8),
    paddingBottom: h(16),
    boxSizing: 'border-box',
  },
  readyInner: {
    flex: 1,
    minHeight: 0,
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    maxWidth: w(2120),
    marginLeft: 'auto',
    marginRight: 'auto',
    alignSelf: 'stretch',
  },
  readySheet: {
    flex: 1,
    minHeight: 0,
    width: '100%',
    maxWidth: w(2120),
    marginLeft: 'auto',
    marginRight: 'auto',
    alignSelf: 'stretch',
    display: 'flex',
    flexDirection: 'column',
    background:
      'radial-gradient(ellipse 72% 42% at 74% 94%, rgba(230, 35, 58, 0.48), rgba(18, 18, 21, 0) 62%), #111113',
    border: '1px solid rgba(255,255,255,0.07)',
    boxShadow: 'inset 0 -120px 180px -155px rgba(230, 35, 58, 0.72)',
  },
  readySheetGlow: {
    position: 'absolute',
    inset: 0,
    pointerEvents: 'none',
    background:
      'radial-gradient(ellipse 72% 46% at 74% 95%, rgba(230, 35, 58, 0.42), transparent 58%)',
  },
  readyHeader: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: h(40),
    paddingBottom: h(18),
    position: 'relative',
    zIndex: 1,
    flexShrink: 0,
  },
  readyLogo: {
    margin: 0,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: '0.28em',
    fontSize: w(37),
    lineHeight: 1,
    letterSpacing: '0.02em',
    textTransform: 'uppercase',
    fontWeight: 400,
  },
  readyContent: {
    flex: 1,
    minHeight: 0,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    padding: `${h(20)} ${w(60)} ${h(82)}`,
    position: 'relative',
    zIndex: 1,
    boxSizing: 'border-box',
  },
  readyNameBadge: {
    margin: `0 0 ${h(28)}`,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: h(58),
    padding: `${h(10)} ${w(42)}`,
    borderRadius: w(18),
    background: ui.color.red,
    color: ui.color.text,
    fontSize: w(34),
    lineHeight: 1,
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: 0,
    boxSizing: 'border-box',
  },
  readyTitle: {
    margin: 0,
    color: ui.color.text,
    fontSize: w(92),
    lineHeight: 1.04,
    fontWeight: 400,
    textTransform: 'uppercase',
    letterSpacing: 0,
  },
  readySubtitle: {
    margin: `${h(32)} 0 0`,
    color: 'rgba(255,255,255,0.76)',
    fontSize: w(40),
    lineHeight: 1.15,
    fontWeight: 400,
    textTransform: 'uppercase',
    letterSpacing: 0,
  },
  readyError: {
    margin: `${h(26)} 0 0`,
    color: '#ff8b96',
    fontSize: w(28),
    lineHeight: 1.2,
    fontWeight: 400,
    textTransform: 'none',
    maxWidth: w(1280),
  },
  headerRow: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: `${h(40)} ${w(50)}`,
    flexShrink: 0,
    position: 'relative',
    zIndex: 1,
  },
  logoMark: {
    margin: 0,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: '0.28em',
    fontSize: w(37),
    lineHeight: 1,
    letterSpacing: '0.02em',
    textTransform: 'uppercase',
    fontWeight: 400,
  },
  namePill: {
    margin: 0,
    padding: `${h(24)} ${w(50)}`,
    borderRadius: w(80),
    fontSize: w(36),
    letterSpacing: '0.05em',
    color: ui.color.text,
    textTransform: 'uppercase',
    fontWeight: 400,
  },
  centerWrap: {
    flex: 1,
    minHeight: h(400),
    display: 'flex',
    flexDirection: 'column',
    /** `center` здесь сжимал блок текста к ширине контента (пол-экрана). Растягиваем на ширину листа, центрируем через `textAlign` на тексте. */
    alignItems: 'stretch',
    justifyContent: 'center',
    width: '100%',
    minWidth: 0,
    padding: `${h(20)} ${w(48)}`,
    position: 'relative',
    zIndex: 1,
    boxSizing: 'border-box',
  },
  goToTreadmillBlock: {
    width: '100%',
    maxWidth: w(2000),
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'stretch',
    justifyContent: 'center',
    textAlign: 'center',
    gap: h(40),
    marginLeft: 'auto',
    marginRight: 'auto',
    boxSizing: 'border-box',
  },
  titleMain: {
    margin: 0,
    textAlign: 'center',
    fontSize: w(82),
    lineHeight: 1.12,
    fontWeight: 400,
    textTransform: 'uppercase',
    color: ui.color.text,
    maxWidth: w(2000),
    width: '100%',
    alignSelf: 'stretch',
    boxSizing: 'border-box',
  },
  titleAccent: {
    color: ui.color.red,
  },
  subtitle: {
    margin: `${h(20)} 0 0`,
    marginLeft: 'auto',
    marginRight: 'auto',
    textAlign: 'center',
    fontSize: w(40),
    lineHeight: 1.5,
    fontWeight: 400,
    color: 'rgba(255,255,255,0.6)',
    textTransform: 'uppercase',
    maxWidth: w(1400),
    width: '100%',
    boxSizing: 'border-box',
  },
  subtitleStrong: {
    color: ui.color.text,
  },
  /** Однострочные подписи под заголовком «Дорожка пока занята» (Figma): серый префикс + белый акцент. */
  queueFigmaSubline: {
    margin: 0,
    marginLeft: 'auto',
    marginRight: 'auto',
    textAlign: 'center',
    fontSize: w(40),
    lineHeight: 1.25,
    fontWeight: 400,
    textTransform: 'none',
    maxWidth: w(2000),
    width: '100%',
    whiteSpace: 'nowrap',
    boxSizing: 'border-box',
  },
  queueFigmaMuted: {
    color: 'rgba(255,255,255,0.6)',
  },
  queueFigmaStrong: {
    color: ui.color.text,
  },
  footerRow: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'nowrap',
    gap: w(32),
    width: '100%',
    flexShrink: 0,
    paddingTop: h(8),
    boxSizing: 'border-box',
  },
  /** Left: outline / transparent; Right: filled grey (Figma 718:895 / 718:924). */
  btnWide: {
    flex: '1 1 0',
    minWidth: 0,
    flexShrink: 0,
    minHeight: h(188),
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: w(48),
    border: '1px solid rgba(255,255,255,0.35)',
    background: 'transparent',
    color: ui.color.text,
    fontSize: w(54),
    fontWeight: 400,
    textTransform: 'uppercase',
    fontFamily: 'inherit',
    cursor: 'pointer',
    boxSizing: 'border-box',
    padding: `${h(32)} ${w(24)}`,
  },
  btnWideSolid: {
    flex: '1 1 0',
    minWidth: 0,
    flexShrink: 0,
    minHeight: h(188),
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: w(48),
    border: '1px solid rgba(255,255,255,0.12)',
    background: 'rgba(255,255,255,0.08)',
    color: '#fff',
    fontSize: w(54),
    fontWeight: 400,
    textTransform: 'uppercase',
    fontFamily: 'inherit',
    cursor: 'pointer',
    boxSizing: 'border-box',
    padding: `${h(32)} ${w(24)}`,
  },
  readyNoButton: {
    flex: '1 1 0',
    minWidth: 0,
    flexShrink: 0,
    minHeight: h(188),
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: w(34),
    border: '1px solid rgba(255,255,255,0.08)',
    background: '#151518',
    color: ui.color.text,
    fontSize: w(54),
    fontWeight: 400,
    textTransform: 'uppercase',
    fontFamily: 'inherit',
    cursor: 'pointer',
    boxSizing: 'border-box',
    padding: `${h(32)} ${w(24)}`,
  },
  readyGoButton: {
    flex: '1 1 0',
    minWidth: 0,
    flexShrink: 0,
    minHeight: h(188),
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: w(34),
    border: '1px solid rgba(255,255,255,0.1)',
    background: ui.color.red,
    color: ui.color.text,
    fontSize: w(54),
    fontWeight: 400,
    textTransform: 'uppercase',
    fontFamily: 'inherit',
    cursor: 'pointer',
    boxSizing: 'border-box',
    padding: `${h(32)} ${w(24)}`,
  },
};
