import type { CSSProperties } from 'react';
import { h, w } from '../../arOzio/dimensions';

export const rs: Record<string, CSSProperties> = {
  heroRoot: {
    flex: 1,
    minHeight: 0,
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    gap: h(31),
    boxSizing: 'border-box',
  },
  heroMain: {
    position: 'relative',
    flex: 1,
    minHeight: 0,
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: '#080809',
    borderRadius: w(70),
    padding: `${h(50)} ${w(50)}`,
    boxSizing: 'border-box',
    overflow: 'hidden',
  },
  heroStack: {
    position: 'relative',
    zIndex: 1,
    flex: 1,
    minHeight: 0,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'stretch',
  },
  heroHeader: {
    display: 'grid',
    gridTemplateColumns: '1fr auto',
    alignItems: 'center',
    width: '100%',
    flexShrink: 0,
    columnGap: w(16),
  },
  heroBody: {
    flex: 1,
    minHeight: 0,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: h(28),
    overflow: 'auto',
    WebkitOverflowScrolling: 'touch' as const,
    paddingTop: h(16),
    paddingBottom: h(16),
    boxSizing: 'border-box',
    width: '100%',
  },
  greeting: {
    margin: 0,
    fontWeight: 400,
    fontSize: w(64),
    lineHeight: 1.1,
    letterSpacing: '0.02em',
    textTransform: 'uppercase',
    textAlign: 'center',
    color: '#ffffff',
    width: '100%',
    maxWidth: w(1900),
  },
  subtitle: {
    margin: 0,
    fontWeight: 400,
    fontSize: w(46),
    lineHeight: 1.4,
    textTransform: 'uppercase',
    textAlign: 'center',
    color: 'rgba(255,255,255,0.76)',
    width: '100%',
    maxWidth: w(1900),
  },
  tabBar: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'stretch',
    width: '100%',
    maxWidth: w(2020),
    backgroundColor: '#262626',
    borderRadius: w(33),
    padding: w(11),
    boxSizing: 'border-box',
    gap: w(8),
  },
  tabBtn: {
    flex: '1 1 0',
    minWidth: 0,
    border: 'none',
    cursor: 'pointer',
    fontFamily: 'inherit',
    borderRadius: w(28),
    padding: `${h(22)} ${w(12)}`,
    fontSize: w(30),
    fontWeight: 400,
    lineHeight: 1.3,
    textTransform: 'uppercase',
    textAlign: 'center',
    transition: 'background-color 0.2s ease, color 0.2s ease',
    WebkitTapHighlightColor: 'transparent',
  },
  tabBtnIdle: {
    backgroundColor: 'transparent',
    color: 'rgba(255,255,255,0.6)',
  },
  tabBtnSelected: {
    backgroundColor: '#ffffff',
    color: '#333333',
  },
  /** ~10% vertical padding (h(52) ≈ 10% of minHeight 520) on the whole title+description block. */
  detailCard: {
    width: '100%',
    maxWidth: w(2020),
    minHeight: h(520),
    backgroundColor: 'rgba(255,255,255,0.07)',
    borderRadius: w(60),
    padding: `${h(52)} ${w(50)}`,
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
  },
  /** Single unit: title + description; internal gap only (no separate description-only padding). */
  detailTextBlock: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: h(30),
    width: '100%',
    maxWidth: w(1800),
    boxSizing: 'border-box',
  },
  detailTitle: {
    margin: 0,
    fontWeight: 400,
    fontSize: w(72),
    lineHeight: 1.1,
    textTransform: 'uppercase',
    color: '#ffffff',
    width: '100%',
  },
  detailDesc: {
    margin: 0,
    fontWeight: 400,
    fontSize: w(40),
    lineHeight: 1.35,
    letterSpacing: '-0.02em',
    color: 'rgba(255,255,255,0.92)',
    textTransform: 'none',
    width: '100%',
    maxWidth: w(1800),
  },
  footerRow: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: w(32),
    width: '100%',
    flexShrink: 0,
    alignItems: 'stretch',
  },
};
