import type { CSSProperties } from 'react';
import { w, h } from '../../arOzio/dimensions';

export const participatePage: Record<string, CSSProperties> = {
  page: {
    width: '100%',
    height: '100%',
    flex: 1,
    minHeight: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: w(24),
    paddingLeft: w(120),
    paddingRight: w(120),
    paddingTop: h(16),
    paddingBottom: h(16),
    boxSizing: 'border-box',
  },
  header: {
    flexShrink: 0,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: h(20),
  },
  logoMark: {
    margin: 0,
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'baseline',
    gap: '0.28em',
    fontSize: w(37),
    lineHeight: 1,
    letterSpacing: '0.02em',
    textTransform: 'uppercase',
    fontWeight: 400,
  },
  logoAmazing: { color: '#ffffff' },
  logoRed: { color: '#e6233a' },
  stepDots: {
    display: 'flex',
    flexDirection: 'row',
    gap: w(16),
    justifyContent: 'center',
    alignItems: 'center',
  },
  sheet: {
    flex: 1,
    minHeight: 0,
    display: 'flex',
    flexDirection: 'column',
    borderRadius: w(48),
    background: '#080809',
    border: '1px solid #1e1e1e',
    boxShadow: 'inset 0 -120px 120px -160px #e6233a',
    overflow: 'hidden',
    padding: `${h(40)} ${w(64)}`,
    boxSizing: 'border-box',
  },
  stepTitle: {
    margin: `0 0 ${h(28)}`,
    fontWeight: 400,
    fontSize: w(56),
    lineHeight: 1.05,
    textTransform: 'uppercase',
    color: '#fff',
    textAlign: 'center',
  },
  formBody: {
    flex: 1,
    minHeight: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: h(28),
    overflow: 'auto',
  },
  label: {
    display: 'flex',
    flexDirection: 'column',
    gap: h(10),
    fontWeight: 400,
    fontSize: w(28),
    textTransform: 'uppercase',
    color: '#c9d1d9',
  },
  input: {
    width: '100%',
    padding: `${h(18)} ${w(24)}`,
    borderRadius: w(20),
    border: '1px solid #30363d',
    backgroundColor: '#1e1e1e',
    color: '#fff',
    fontSize: w(32),
    textTransform: 'none',
    outline: 'none',
    boxSizing: 'border-box',
    transition: 'border-color 0.2s ease, box-shadow 0.2s ease',
  },
  error: {
    color: '#f85149',
    margin: 0,
    fontSize: w(24),
    textTransform: 'none',
  },
  choiceRow: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: w(16),
  },
  choiceGrid3: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr 1fr',
    gap: w(16),
  },
  choiceBtn: {
    flex: '1 1 0',
    minWidth: 0,
    padding: `${h(20)} ${w(20)}`,
    borderRadius: w(20),
    border: '1px solid #30363d',
    backgroundColor: '#1e1e1e',
    color: '#8b949e',
    fontWeight: 400,
    fontSize: w(28),
    textTransform: 'uppercase',
    cursor: 'pointer',
    transition: 'background-color 0.2s ease, color 0.2s ease, border-color 0.2s ease, transform 0.15s ease',
  },
  choiceBtnActive: {
    backgroundColor: '#e6233a',
    color: '#fff',
    borderColor: '#e6233a',
  },
  footer: {
    flexShrink: 0,
    display: 'flex',
    flexDirection: 'row',
    gap: w(32),
    marginTop: h(28),
  },
  btnGhost: {
    flex: '1 1 0',
    minWidth: 0,
    minHeight: h(100),
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: '#000',
    color: '#fff',
    fontWeight: 400,
    fontSize: w(36),
    lineHeight: 1,
    textTransform: 'uppercase',
    textDecoration: 'none',
    borderRadius: w(36),
    border: '1px solid #1e1e1e',
    boxSizing: 'border-box',
    cursor: 'pointer',
    transition: 'background-color 0.2s ease, border-color 0.2s ease',
  },
  btnPrimary: {
    flex: '1 1 0',
    minWidth: 0,
    minHeight: h(100),
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: '#e6233a',
    color: '#fff',
    fontWeight: 400,
    fontSize: w(36),
    lineHeight: 1,
    textTransform: 'uppercase',
    textDecoration: 'none',
    border: 'none',
    borderRadius: w(36),
    boxSizing: 'border-box',
    cursor: 'pointer',
    transition: 'background-color 0.2s ease, transform 0.15s ease',
  },
  btnPrimaryDisabled: {
    opacity: 0.5,
    cursor: 'not-allowed',
  },
  summaryRow: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: w(24),
    padding: `${h(16)} 0`,
    borderBottom: '1px solid #30363d',
    fontSize: w(30),
    textTransform: 'uppercase',
    color: '#c9d1d9',
  },
  summaryValue: {
    color: '#fff',
    textAlign: 'right',
    textTransform: 'none',
    fontWeight: 400,
  },
};
