import type { CSSProperties } from 'react';
import { w, h } from '../../arOzio/dimensions';

/** Inner column inside `ScreenContainer` (padding applied by screen layout). */
export const reg: Record<string, CSSProperties> = {
  page: {
    width: '100%',
    height: '100%',
    flex: 1,
    minHeight: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: h(16),
    boxSizing: 'border-box',
  },
  header: {
    display: 'grid',
    gridTemplateColumns: `${w(140)} 1fr ${w(140)}`,
    alignItems: 'center',
    flexShrink: 0,
  },
  back: {
    justifySelf: 'start',
    color: '#8b949e',
    fontSize: w(24),
    textDecoration: 'none',
    textTransform: 'none',
    border: 'none',
    background: 'none',
    cursor: 'pointer',
    fontFamily: 'inherit',
    padding: 0,
  },
  logoMark: {
    margin: 0,
    justifySelf: 'center',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: '0.28em',
    fontSize: w(37),
    lineHeight: 1,
    letterSpacing: '0.02em',
    textTransform: 'uppercase',
    fontWeight: 400,
  },
  logoRed: { color: '#e6233a' },
  headerSpacer: { width: w(140) },
  title: {
    margin: 0,
    textAlign: 'center',
    fontWeight: 400,
    fontSize: w(44),
    lineHeight: 1.1,
    textTransform: 'uppercase',
    color: '#fff',
  },
  subtitle: {
    margin: 0,
    textAlign: 'center',
    fontSize: w(24),
    color: '#8b949e',
    textTransform: 'none',
  },
  question: {
    margin: 0,
    fontWeight: 400,
    fontSize: w(36),
    lineHeight: 1.2,
    textTransform: 'uppercase',
    color: '#fff',
    textAlign: 'center',
  },
  error: {
    margin: 0,
    textAlign: 'center',
    color: '#f85149',
    fontSize: w(22),
    textTransform: 'none',
  },
  warnBanner: {
    margin: 0,
    padding: h(16),
    borderRadius: w(20),
    background: '#1e1e1e',
    border: '1px solid #e6233a',
    color: '#fff',
    fontSize: w(26),
    textAlign: 'center',
    textTransform: 'none',
  },
  choiceRow: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: w(16),
    justifyContent: 'center',
  },
  choiceBtn: {
    flex: '1 1 200px',
    maxWidth: w(400),
    minHeight: h(88),
    padding: `${h(20)} ${w(24)}`,
    borderRadius: w(20),
    border: '1px solid #30363d',
    backgroundColor: '#1e1e1e',
    color: '#8b949e',
    fontWeight: 400,
    fontSize: w(28),
    textTransform: 'uppercase',
    cursor: 'pointer',
    transition: 'background-color 0.2s ease, color 0.2s ease, border-color 0.2s ease',
  },
  choiceBtnActive: {
    backgroundColor: '#e6233a',
    color: '#fff',
    borderColor: '#e6233a',
  },
  label: {
    display: 'flex',
    flexDirection: 'column',
    gap: h(12),
    fontWeight: 400,
    fontSize: w(28),
    textTransform: 'uppercase',
    color: '#c9d1d9',
    textAlign: 'left',
  },
  input: {
    width: '100%',
    padding: `${h(20)} ${w(24)}`,
    borderRadius: w(20),
    border: '1px solid #30363d',
    backgroundColor: '#1e1e1e',
    color: '#fff',
    fontSize: w(32),
    textTransform: 'none',
    outline: 'none',
    boxSizing: 'border-box',
  },
  inputError: {
    borderColor: '#f85149',
  },
  footer: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: w(24),
    width: '100%',
    flexShrink: 0,
    marginTop: h(8),
  },
  btnGhost: {
    flex: '1 1 200px',
    minHeight: h(96),
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: '#000',
    color: '#fff',
    fontWeight: 400,
    fontSize: w(32),
    lineHeight: 1,
    textTransform: 'uppercase',
    textDecoration: 'none',
    borderRadius: w(36),
    border: '1px solid #1e1e1e',
    boxSizing: 'border-box',
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
  btnPrimary: {
    flex: '1 1 200px',
    minHeight: h(96),
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: '#e6233a',
    color: '#fff',
    fontWeight: 400,
    fontSize: w(32),
    lineHeight: 1,
    textTransform: 'uppercase',
    textDecoration: 'none',
    borderRadius: w(36),
    border: 'none',
    boxSizing: 'border-box',
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
  btnPrimaryDisabled: {
    opacity: 0.45,
    cursor: 'not-allowed',
  },
  checkboxRow: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: w(16),
  },
  checkbox: {
    width: w(28),
    height: w(28),
    marginTop: h(4),
    flexShrink: 0,
    cursor: 'pointer',
    accentColor: '#e6233a',
  },
  checkboxLabel: {
    fontSize: w(24),
    lineHeight: 1.35,
    color: '#c9d1d9',
    textTransform: 'none',
    fontWeight: 400,
  },
  introCenter: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: h(32),
    textAlign: 'center',
    padding: `${h(24)} 0`,
  },
  /** Age / gender steps — headline outside gray card (Figma AR x OZIO iPad) */
  earlyStepWrap: {
    flex: 1,
    minHeight: 0,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'stretch',
    gap: h(40),
    padding: `${h(8)} 0`,
    boxSizing: 'border-box',
  },
  earlyStepQuestion: {
    margin: 0,
    fontWeight: 400,
    fontSize: w(52),
    lineHeight: 1.12,
    textTransform: 'uppercase',
    color: '#fff',
    textAlign: 'center',
    letterSpacing: '0.02em',
    maxWidth: 'min(92vw, 1200px)',
    alignSelf: 'center',
  },
  /** Same typography as earlyStepQuestion, split into two lines (age frame 697:489) */
  earlyStepQuestionStack: {
    margin: 0,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: h(12),
    fontWeight: 400,
    fontSize: w(52),
    lineHeight: 1.12,
    textTransform: 'uppercase',
    color: '#fff',
    textAlign: 'center',
    letterSpacing: '0.02em',
    maxWidth: 'min(92vw, 1200px)',
    alignSelf: 'center',
  },
  earlyStepCard: {
    width: '100%',
    maxWidth: w(1400),
    alignSelf: 'center',
    backgroundColor: '#1e1e1e',
    border: '1px solid #2d2d2d',
    borderRadius: w(40),
    padding: `${h(56)} ${w(72)}`,
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: h(36),
    boxShadow: '0 24px 80px rgba(0,0,0,0.45)',
  },
  earlyStepBtnRow: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: w(28),
    justifyContent: 'center',
    alignItems: 'stretch',
  },
  earlyStepBtn: {
    flex: '1 1 280px',
    maxWidth: w(560),
    minHeight: h(120),
    padding: `${h(28)} ${w(40)}`,
    borderRadius: w(28),
    border: '2px solid #3d3d42',
    backgroundColor: '#2a2a2c',
    color: '#e6edf3',
    fontWeight: 400,
    fontSize: w(36),
    lineHeight: 1.1,
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
    cursor: 'pointer',
    fontFamily: 'inherit',
    transition: 'background-color 0.2s ease, border-color 0.2s ease, color 0.2s ease, transform 0.15s ease',
  },
  earlyStepWarnInCard: {
    margin: 0,
    padding: h(24),
    borderRadius: w(24),
    background: '#141414',
    border: '1px solid #e6233a',
    color: '#fff',
    fontSize: w(28),
    textAlign: 'center',
    textTransform: 'none',
    lineHeight: 1.4,
  },
  earlyStepHomeLink: {
    flex: '1 1 100%',
    minHeight: h(104),
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: '#000',
    color: '#fff',
    fontWeight: 400,
    fontSize: w(32),
    lineHeight: 1,
    textTransform: 'uppercase',
    textDecoration: 'none',
    borderRadius: w(32),
    border: '1px solid #30363d',
    boxSizing: 'border-box',
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
  /** Figma 691:529 — Подтверждение возраста (dev handoff) */
  ageFigmaRoot: {
    flex: 1,
    minHeight: 0,
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'stretch',
    justifyContent: 'center',
    gap: h(31),
    boxSizing: 'border-box',
  },
  ageFigmaMain: {
    position: 'relative',
    flex: 1,
    minHeight: 0,
    display: 'flex',
    flexDirection: 'column',
    padding: `${h(50)} ${w(50)}`,
    boxSizing: 'border-box',
  },
  ageFigmaBgHost: {
    position: 'absolute',
    inset: 0,
    pointerEvents: 'none',
    zIndex: 0,
    overflow: 'hidden',
  },
  ageFigmaBgWash: {
    position: 'absolute',
    inset: 0,
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(255,255,255,0.04)',
  },
  /** Figma mesh / gradient bitmap: use as CSS background (no img stretch, no tiling). */
  ageFigmaBgRectLayer: {
    position: 'absolute',
    inset: 0,
    backgroundSize: 'cover',
    backgroundPosition: 'center',
    backgroundRepeat: 'no-repeat',
    opacity: 0.12,
    pointerEvents: 'none' as const,
  },
  /** Smooth depth on top of bitmap (avoids harsh banding from low-opacity texture). */
  ageFigmaBgSmoothSheen: {
    position: 'absolute',
    inset: 0,
    pointerEvents: 'none' as const,
    background: `linear-gradient(
      155deg,
      rgba(255,255,255,0.04) 0%,
      transparent 38%,
      transparent 62%,
      rgba(230,35,58,0.045) 100%
    )`,
  },
  ageFigmaBlobA: {
    position: 'absolute',
    right: '-15%',
    bottom: '-25%',
    width: '110%',
    height: 'auto',
    maxWidth: 'none',
    opacity: 0.22,
    display: 'block',
  },
  ageFigmaBlobB: {
    position: 'absolute',
    left: '-10%',
    bottom: '-20%',
    width: '95%',
    height: 'auto',
    opacity: 0.18,
    display: 'block',
  },
  ageFigmaStack: {
    position: 'relative',
    zIndex: 1,
    flex: 1,
    minHeight: 0,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'stretch',
  },
  ageFigmaHeader: {
    display: 'grid',
    gridTemplateColumns: '1fr auto 1fr',
    alignItems: 'center',
    width: '100%',
    flexShrink: 0,
    columnGap: w(16),
  },
  ageFigmaPill: {
    justifySelf: 'start',
    display: 'inline-flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: w(10),
    padding: `${h(30)} ${w(50)}`,
    borderRadius: w(80),
    border: '1px solid rgba(255,255,255,0.3)',
    backgroundColor: 'transparent',
    color: '#ffffff',
    fontSize: w(22),
    fontWeight: 400,
    letterSpacing: '1.1px',
    textTransform: 'uppercase',
    cursor: 'pointer',
    fontFamily: 'inherit',
    lineHeight: 1,
  },
  ageFigmaPillLink: {
    justifySelf: 'end',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: `${h(30)} ${w(50)}`,
    borderRadius: w(80),
    border: '1px solid rgba(255,255,255,0.3)',
    backgroundColor: 'transparent',
    color: '#ffffff',
    fontSize: w(22),
    fontWeight: 400,
    letterSpacing: '1.1px',
    textTransform: 'uppercase',
    textDecoration: 'none',
    fontFamily: 'inherit',
    lineHeight: 1,
    cursor: 'pointer',
    boxSizing: 'border-box',
  },
  ageFigmaLogo: {
    justifySelf: 'center',
    margin: 0,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: '0.28em',
    fontSize: w(37),
    lineHeight: 1,
    letterSpacing: '0.02em',
    textTransform: 'uppercase',
    fontWeight: 400,
  },
  ageFigmaQuestion: {
    margin: 0,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: h(8),
    maxWidth: w(1555),
    width: '100%',
    fontWeight: 400,
    fontSize: w(82),
    lineHeight: 1.05,
    letterSpacing: '0.02em',
    textTransform: 'uppercase',
    textAlign: 'center',
    color: '#ffffff',
    whiteSpace: 'nowrap',
  },
  ageFigmaBlockedText: {
    margin: 0,
    fontSize: w(32),
    lineHeight: 1.35,
    textAlign: 'center',
    color: 'rgba(255,255,255,0.92)',
    textTransform: 'none',
    fontWeight: 400,
    maxWidth: w(1200),
  },
  ageFigmaButtonRow: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: w(32),
    width: '100%',
    flexShrink: 0,
    alignItems: 'stretch',
  },
  ageFigmaChoiceBtn: {
    flex: '1 1 300px',
    minHeight: h(263),
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: `${h(93)} ${w(48)}`,
    borderRadius: w(48),
    border: 'none',
    backgroundColor: 'rgba(255,255,255,0.08)',
    color: '#ffffff',
    fontSize: w(64),
    fontWeight: 400,
    lineHeight: 1,
    textTransform: 'uppercase',
    letterSpacing: '0.02em',
    cursor: 'pointer',
    fontFamily: 'inherit',
    boxSizing: 'border-box',
    WebkitTapHighlightColor: 'transparent',
  },
  ageFigmaChoiceBtnLink: {
    flex: '1 1 100%',
    minHeight: h(263),
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: `${h(93)} ${w(48)}`,
    borderRadius: w(48),
    border: '1px solid rgba(255,255,255,0.3)',
    backgroundColor: 'rgba(255,255,255,0.06)',
    color: '#ffffff',
    fontSize: w(40),
    fontWeight: 400,
    lineHeight: 1,
    textTransform: 'uppercase',
    textDecoration: 'none',
    fontFamily: 'inherit',
    boxSizing: 'border-box',
    cursor: 'pointer',
  },
  wizardBody: {
    flex: 1,
    minHeight: 0,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'stretch',
    overflow: 'auto',
    WebkitOverflowScrolling: 'touch' as const,
  },
  /** Name / phone steps: fit frame without inner scroll (Figma iPad). */
  wizardBodyShort: {
    overflow: 'hidden',
  },
  /** Short steps: outer + inner centering (name, phone). */
  stepBodyOuter: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    minHeight: 0,
    overflow: 'hidden',
    boxSizing: 'border-box',
  },
  stepBodyInner: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    minHeight: 0,
    overflow: 'hidden',
    boxSizing: 'border-box',
    gap: h(24),
    alignItems: 'stretch',
    width: '100%',
    maxWidth: w(1760),
    alignSelf: 'center',
  },
  /** Tall steps: single centered column (age unanswered, gender). */
  stepBodyTall: {
    flex: 1,
    minHeight: 0,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '2cqh 0',
    boxSizing: 'border-box',
    width: '100%',
  },
  stepTitle: {
    margin: 0,
    textAlign: 'center' as const,
  },
  stepErrorCentered: {
    margin: 0,
    textAlign: 'center' as const,
  },
  /** Underline-only inputs (Figma) — no fill, no side borders. */
  wizardFieldUnderline: {
    border: 'none',
    borderRadius: 0,
    backgroundColor: 'transparent',
    outline: 'none',
    boxShadow: 'none',
    WebkitAppearance: 'none' as const,
    appearance: 'none' as const,
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'rgba(128, 128, 129, 0.55)',
    paddingBottom: h(10),
    margin: 0,
    fontFamily: 'inherit',
    boxSizing: 'border-box',
  },
  wizardFieldUnderlineError: {
    borderBottomColor: '#f85149',
  },
  nameFormRow: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'nowrap',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: w(24),
    boxSizing: 'border-box',
    width: '100%',
    marginTop: 0,
    flexShrink: 0,
  },
  nameFieldInline: {
    flex: 1,
    minWidth: 0,
    paddingTop: '30px',
  },
  nameFieldsCluster: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'nowrap',
    alignItems: 'center',
    gap: w(24),
    flex: 1,
    minWidth: 0,
  },
  nameFieldCol: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: h(16),
    minWidth: 0,
  },
  nameFieldInlineError: {
    margin: 0,
    paddingLeft: w(40),
    paddingRight: w(40),
    color: '#f85149',
    fontSize: w(22),
    lineHeight: 1.2,
    textTransform: 'none',
    textAlign: 'left',
    minHeight: h(28),
  },
  nameFieldLabel: {
    margin: 0,
    paddingLeft: w(40),
    paddingRight: w(40),
    fontSize: w(48),
    fontWeight: 400,
    color: '#808081',
    textTransform: 'uppercase',
    lineHeight: 1,
  },
  nameFieldInput: {
    paddingLeft: w(40),
    paddingRight: w(40),
    width: '100%',
    color: '#ffffff',
    fontSize: w(48),
    fontWeight: 400,
    textTransform: 'uppercase',
  },
  nameNextBtn: {
    flex: '0 0 auto',
    padding: `${h(30)} ${w(80)}`,
    borderRadius: w(36),
    backgroundColor: '#262627',
    color: '#808081',
    fontSize: w(48),
    fontWeight: 400,
    textTransform: 'uppercase',
    cursor: 'pointer',
    fontFamily: 'inherit',
    lineHeight: 1,
  },
  nameNextBtnActive: {
    backgroundColor: '#e6233a',
    color: '#ffffff',
    cursor: 'pointer',
  },
  keypadPanel: {
    width: '100%',
    minHeight: h(550),
    flexShrink: 0,
    backgroundColor: '#1b1b1b',
    borderRadius: w(50),
    padding: `${h(40)} ${w(64)}`,
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    gap: h(36),
    overflow: 'hidden',
  },
  keypadRow: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: w(36),
    justifyContent: 'center',
    alignItems: 'center',
  },
  keypadKey: {
    width: w(133),
    height: h(133),
    minWidth: w(120),
    minHeight: h(120),
    flex: '0 0 auto',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: w(24),
    border: `${w(10)} solid #3f3f3f`,
    backgroundColor: '#515151',
    color: '#ffffff',
    fontSize: w(48),
    fontWeight: 400,
    fontFamily: 'inherit',
    cursor: 'pointer',
    textTransform: 'uppercase',
    boxSizing: 'border-box',
    padding: 0,
  },
  keypadKeyWide: {
    width: w(308),
    minWidth: w(280),
  },
  keypadKeyGrow: {
    flex: '1 1 200px',
    maxWidth: w(470),
    width: 'auto',
  },
  /** Phone underline + «Далее» on one row, baseline-aligned (Figma). */
  phoneFieldButtonRow: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'nowrap',
    alignItems: 'flex-end',
    justifyContent: 'center',
    gap: w(40),
    width: '100%',
    maxWidth: w(1600),
    alignSelf: 'center',
    boxSizing: 'border-box',
    paddingLeft: w(32),
    paddingRight: w(32),
  },
  /** +7 and digits on one row; one bottom rule (Figma). */
  phoneInputUnderlineWrap: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'nowrap',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: w(20),
    flex: '1 1 0',
    minWidth: 0,
    maxWidth: 'none',
    boxSizing: 'border-box',
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'rgba(128, 128, 129, 0.55)',
    paddingBottom: h(10),
    paddingLeft: w(8),
    paddingRight: w(8),
  },
  phoneNextBtn: {
    flexShrink: 0,
    alignSelf: 'flex-end',
  },
  phoneCountryPrefix: {
    flexShrink: 0,
    margin: 0,
    padding: 0,
    color: '#ffffff',
    fontSize: w(64),
    fontWeight: 400,
    lineHeight: 1.15,
    textTransform: 'none',
  },
  phoneDigitsInput: {
    flex: 1,
    minWidth: 0,
    fontSize: w(64),
    fontWeight: 400,
    color: '#ffffff',
    textAlign: 'left',
    letterSpacing: '0.04em',
    lineHeight: 1.15,
  },
  consentCenter: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: h(97),
    paddingTop: h(24),
    paddingBottom: h(24),
    paddingLeft: w(16),
    paddingRight: w(16),
    boxSizing: 'border-box',
    width: '100%',
    maxWidth: w(1760),
    alignSelf: 'center',
    minHeight: 0,
  },
  consentErrorStack: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: h(8),
    width: '100%',
  },
  /** Figma 691:2854 — two lines; slightly smaller than 82px frame text for clean wrap on iPad. */
  consentHeading: {
    margin: 0,
    fontSize: w(70),
    lineHeight: 1.12,
    fontWeight: 400,
    textAlign: 'center',
    textTransform: 'uppercase',
    color: '#ffffff',
    maxWidth: w(1436),
    width: '100%',
    alignSelf: 'center',
  },
  consentHeadingLine: {
    display: 'block',
    textAlign: 'center',
    whiteSpace: 'nowrap',
  },
  /** Two equal columns; group centered with max-width so outer / gap / outer balance (Figma). */
  consentCardsRow: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'stretch',
    gap: w(40),
    width: '100%',
    maxWidth: w(2000),
    marginLeft: 'auto',
    marginRight: 'auto',
    boxSizing: 'border-box',
  },
  /** Single style for both consent cards (rules + personal data). */
  consentCard: {
    flex: '1 1 0',
    minWidth: w(680),
    maxWidth: w(980),
    minHeight: 0,
    backgroundColor: 'rgba(217,217,217,0.1)',
    borderRadius: w(40),
    padding: `${h(22)} ${w(36)} ${h(22)} ${w(28)}`,
    boxSizing: 'border-box',
    overflow: 'hidden',
    alignSelf: 'stretch',
  },
  consentCardInner: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: w(30),
    minHeight: 0,
  },
  /** Figma 717:550 / 744:270 — 120×120, r36; unchecked = empty well; checked = red tile + check (718:570). */
  consentCheckLabel: {
    position: 'relative',
    width: w(120),
    height: w(120),
    flexShrink: 0,
    display: 'block',
    cursor: 'pointer',
    WebkitTapHighlightColor: 'transparent',
  },
  consentCheckInput: {
    position: 'absolute',
    inset: 0,
    width: '100%',
    height: '100%',
    margin: 0,
    opacity: 0,
    cursor: 'pointer',
    zIndex: 2,
  },
  consentCheckFrame: {
    position: 'absolute',
    inset: 0,
    width: w(120),
    height: w(120),
    borderRadius: w(36),
    backgroundColor: 'rgba(0,0,0,0.32)',
    boxSizing: 'border-box',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    pointerEvents: 'none' as const,
    transition: 'transform 0.12s ease',
  },
  consentCheckMark: {
    width: w(102),
    height: w(102),
    borderRadius: w(32),
    backgroundColor: '#e6233a',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  consentCardTextCol: {
    display: 'flex',
    flexDirection: 'column',
    gap: h(14),
    alignItems: 'flex-start',
    justifyContent: 'center',
    minWidth: 0,
    flex: '1 1 auto',
  },
  consentCardTitle: {
    margin: 0,
    fontSize: w(36),
    lineHeight: 1.22,
    fontWeight: 400,
    color: '#ffffff',
    textTransform: 'uppercase',
    textAlign: 'left',
    whiteSpace: 'nowrap',
  },
  consentReadBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: h(84),
    padding: `${h(20)} ${w(64)}`,
    borderRadius: w(42),
    border: '1px solid rgba(255,255,255,0.5)',
    background: 'transparent',
    color: '#ffffff',
    fontSize: w(24),
    fontWeight: 400,
    textTransform: 'uppercase',
    fontFamily: 'inherit',
    cursor: 'pointer',
  },
  consentSubmitBtn: {
    flex: '1 1 100%',
    minHeight: h(263),
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: `${h(93)} ${w(48)}`,
    borderRadius: w(48),
    border: 'none',
    backgroundColor: '#4b4b4b',
    color: '#ffffff',
    fontSize: w(64),
    fontWeight: 400,
    textTransform: 'uppercase',
    fontFamily: 'inherit',
    cursor: 'pointer',
    boxSizing: 'border-box',
    boxShadow: 'inset 0 20px 30px rgba(158,158,158,0.22)',
    transition: 'opacity 0.2s ease, background-color 0.2s ease',
  },
  consentSubmitBtnDisabled: {
    opacity: 0.5,
    cursor: 'not-allowed',
  },
  consentSubmitBtnReady: {
    backgroundColor: '#e6233a',
    opacity: 1,
    cursor: 'pointer',
    boxShadow: 'none',
  },
};
